import { createSlice } from '@reduxjs/toolkit';
import { AppState } from 'utils/types';

const initialAppState: AppState = {
    selectedContentItem: undefined
};

/**
 * This portion of the state is used to control the layout of the app. For a simple
 * app such as this, the only requirement is to keep track of what item is selected.
 */
const appSlice = createSlice({
    name: 'app',
    initialState: initialAppState,
    reducers: {
        contentItemSelected: (state, { payload }) => {
            state.selectedContentItem = payload;
        }
    }
});

// Redux actions automatically generated by redux toolkit based on the reducer names
export const { contentItemSelected } = appSlice.actions;

export default appSlice;