import { createApi, fetchBaseQuery } from '@reduxjs/toolkit/query/react'

/**
 * A redux toolkit API slice that is used to fetch the table of Contents.
 */
export const contentApiSlice = createApi({
    reducerPath: 'contentApi',
    baseQuery: fetchBaseQuery({ baseUrl: 'http://localhost:3004' }),
    endpoints: (builder) => ({

        getContentItems: builder.query({
            query: () => `/data`
        })
    }),
});

// Hooks are automatically generated by redux toolkit based on the endpoint names
export const { useGetContentItemsQuery } = contentApiSlice;